services:
  ftp:
      container_name: ftp-server
      image: garethflowers/ftp-server
      environment:
        - FTP_USER=${FTP_USERNAME}
        - FTP_PASS=${FTP_PASSWORD}
      ports:
        - '20-21:20-21/tcp'
        - '40000-40009:40000-40009/tcp'   # passive mode
      volumes:
          - ./shared:/home/${FTP_USERNAME}/shared
      networks:
        - surface_default
networks:
  surface_default:
    external: true
